# Generated by Django 4.0.3 on 2022-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('what_you_need', models.CharField(max_length=35)),
                ('flow_speed', models.CharField(max_length=35)),
                ('sweat_factor', models.CharField(max_length=40)),
                ('zen_factor', models.CharField(max_length=35)),
            ],
        ),
    ]
